[2024-10-25T23:00:46.473+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T23:00:46.491+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T23:00:39.605539+00:00 [queued]>
[2024-10-25T23:00:46.502+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T23:00:39.605539+00:00 [queued]>
[2024-10-25T23:00:46.503+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-25T23:00:46.522+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_data_to_mongo> on 2024-10-25 23:00:39.605539+00:00
[2024-10-25T23:00:46.530+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-25T23:00:46.532+0000] {standard_task_runner.py:72} INFO - Started process 139 to run task
[2024-10-25T23:00:46.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'inserir_dados_mongodb', 'insert_data_to_mongo', 'manual__2024-10-25T23:00:39.605539+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dag_save_mongodb_v3.py', '--cfg-path', '/tmp/tmpee4f0qbn']
[2024-10-25T23:00:46.537+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask insert_data_to_mongo
[2024-10-25T23:00:46.592+0000] {task_command.py:467} INFO - Running <TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T23:00:39.605539+00:00 [running]> on host 9e883d86a6d2
[2024-10-25T23:00:46.690+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='inserir_dados_mongodb' AIRFLOW_CTX_TASK_ID='insert_data_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T23:00:39.605539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T23:00:39.605539+00:00'
[2024-10-25T23:00:46.692+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T23:00:46.769+0000] {logging_mixin.py:190} INFO - Registro com id 1 já existe. Não será inserido.
[2024-10-25T23:00:46.772+0000] {logging_mixin.py:190} INFO - Registro com id 2 já existe. Não será inserido.
[2024-10-25T23:00:46.775+0000] {logging_mixin.py:190} INFO - Registro com id 3 já existe. Não será inserido.
[2024-10-25T23:00:46.777+0000] {logging_mixin.py:190} INFO - Registro com id 4 já existe. Não será inserido.
[2024-10-25T23:00:46.779+0000] {logging_mixin.py:190} INFO - Registro com id 5 já existe. Não será inserido.
[2024-10-25T23:00:46.780+0000] {logging_mixin.py:190} INFO - Nenhum novo registro para inserir.
[2024-10-25T23:00:46.783+0000] {logging_mixin.py:190} INFO - Total de documentos na coleção 'clientes': 5
[2024-10-25T23:00:46.785+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T23:00:46.814+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T23:00:46.816+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=inserir_dados_mongodb, task_id=insert_data_to_mongo, run_id=manual__2024-10-25T23:00:39.605539+00:00, execution_date=20241025T230039, start_date=20241025T230046, end_date=20241025T230046
[2024-10-25T23:00:46.873+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T23:00:46.893+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T23:00:46.896+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
