[2024-10-25T21:42:08.557+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T21:42:08.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T21:42:01.888805+00:00 [queued]>
[2024-10-25T21:42:08.583+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T21:42:01.888805+00:00 [queued]>
[2024-10-25T21:42:08.583+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-25T21:42:08.601+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_data_to_mongo> on 2024-10-25 21:42:01.888805+00:00
[2024-10-25T21:42:08.606+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2048) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-25T21:42:08.608+0000] {standard_task_runner.py:72} INFO - Started process 2050 to run task
[2024-10-25T21:42:08.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'inserir_dados_mongodb', 'insert_data_to_mongo', 'manual__2024-10-25T21:42:01.888805+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dag_save_mongodb_v3.py', '--cfg-path', '/tmp/tmpf3okjo00']
[2024-10-25T21:42:08.613+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask insert_data_to_mongo
[2024-10-25T21:42:08.663+0000] {task_command.py:467} INFO - Running <TaskInstance: inserir_dados_mongodb.insert_data_to_mongo manual__2024-10-25T21:42:01.888805+00:00 [running]> on host f31c2b905d22
[2024-10-25T21:42:08.753+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='inserir_dados_mongodb' AIRFLOW_CTX_TASK_ID='insert_data_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T21:42:01.888805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T21:42:01.888805+00:00'
[2024-10-25T21:42:08.754+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T21:42:08.830+0000] {logging_mixin.py:190} INFO - Registro com id 1 já existe. Não será inserido.
[2024-10-25T21:42:08.832+0000] {logging_mixin.py:190} INFO - Registro com id 2 já existe. Não será inserido.
[2024-10-25T21:42:08.833+0000] {logging_mixin.py:190} INFO - Registro com id 3 já existe. Não será inserido.
[2024-10-25T21:42:08.835+0000] {logging_mixin.py:190} INFO - Registro com id 4 já existe. Não será inserido.
[2024-10-25T21:42:08.837+0000] {logging_mixin.py:190} INFO - Registro com id 5 já existe. Não será inserido.
[2024-10-25T21:42:08.838+0000] {logging_mixin.py:190} INFO - Nenhum novo registro para inserir.
[2024-10-25T21:42:08.839+0000] {logging_mixin.py:190} INFO - Total de documentos na coleção 'clientes': 5
[2024-10-25T21:42:08.840+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T21:42:08.852+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T21:42:08.853+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=inserir_dados_mongodb, task_id=insert_data_to_mongo, run_id=manual__2024-10-25T21:42:01.888805+00:00, execution_date=20241025T214201, start_date=20241025T214208, end_date=20241025T214208
[2024-10-25T21:42:08.906+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T21:42:08.924+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T21:42:08.933+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
