[2024-09-28T19:52:47.173+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:52:47.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:52:47.176+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:52:47.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:52:47.210+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:52:47.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:52:47.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:52:47.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.057 seconds
[2024-09-28T19:53:17.708+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:17.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:53:17.711+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:53:17.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:17.734+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:53:17.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:53:17.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:17.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.044 seconds
[2024-09-28T19:53:48.689+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:48.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:53:48.691+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:53:48.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:48.703+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:53:48.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:53:48.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:53:48.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.031 seconds
[2024-09-28T19:54:18.797+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:18.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:54:18.799+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:54:18.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:18.817+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:54:18.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:54:18.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:18.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.038 seconds
[2024-09-28T19:54:49.417+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:49.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:54:49.420+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:54:49.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:49.430+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:54:49.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:54:49.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:54:49.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.031 seconds
[2024-09-28T19:55:19.582+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:19.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:55:19.584+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:19.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:19.596+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:19.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-28T19:55:19.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:19.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.032 seconds
[2024-09-28T19:55:39.892+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:39.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:55:39.895+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:39.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:40.101+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:40.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 9, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:55:40.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:40.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.235 seconds
[2024-09-28T19:55:40.942+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:40.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:55:40.944+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:40.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:40.972+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:55:40.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:55:40.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:55:40.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.055 seconds
[2024-09-28T19:56:11.315+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:11.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:56:11.318+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:56:11.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:11.342+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:56:11.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:56:11.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:11.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.049 seconds
[2024-09-28T19:56:41.704+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:41.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:56:41.707+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:56:41.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:41.721+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:56:41.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:56:41.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:56:41.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.034 seconds
[2024-09-28T19:57:12.097+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:12.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:57:12.100+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:57:12.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:12.115+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:57:12.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:57:12.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:12.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.037 seconds
[2024-09-28T19:57:42.256+0000] {processor.py:186} INFO - Started process (PID=706) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:42.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:57:42.258+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:57:42.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:42.282+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:57:42.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:57:42.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:57:42.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.043 seconds
[2024-09-28T19:58:13.262+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:13.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:58:13.265+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:58:13.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:13.288+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:58:13.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:58:13.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:13.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.042 seconds
[2024-09-28T19:58:44.279+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:44.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:58:44.282+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:58:44.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:44.294+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:58:44.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:58:44.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:58:44.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.035 seconds
[2024-09-28T19:59:14.754+0000] {processor.py:186} INFO - Started process (PID=901) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:14.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:59:14.757+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:59:14.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:14.802+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:59:14.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:59:14.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:14.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.070 seconds
[2024-09-28T19:59:45.046+0000] {processor.py:186} INFO - Started process (PID=966) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:45.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T19:59:45.049+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:59:45.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:45.060+0000] {logging_mixin.py:190} INFO - [2024-09-28T19:59:45.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T19:59:45.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T19:59:45.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.031 seconds
[2024-09-28T20:00:15.455+0000] {processor.py:186} INFO - Started process (PID=1031) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:00:15.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:00:15.458+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:00:15.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:00:15.502+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:00:15.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:00:15.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:00:15.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.063 seconds
[2024-09-28T20:05:07.638+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:07.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:05:07.640+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:05:07.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:07.655+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:05:07.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:05:07.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:07.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.036 seconds
[2024-09-28T20:05:38.405+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:38.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:05:38.408+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:05:38.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:38.422+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:05:38.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:05:38.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:05:38.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.036 seconds
[2024-09-28T20:06:08.863+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:08.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:06:08.865+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:06:08.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:08.877+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:06:08.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:06:08.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:08.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.031 seconds
[2024-09-28T20:06:39.414+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:39.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:06:39.416+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:06:39.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:39.424+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:06:39.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:06:39.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:06:39.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.027 seconds
[2024-09-28T20:07:09.637+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:09.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:07:09.639+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:09.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:09.649+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:09.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:07:09.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:09.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.028 seconds
[2024-09-28T20:07:40.462+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:40.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:07:40.464+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:40.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:40.480+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:40.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:07:40.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:40.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.035 seconds
[2024-09-28T20:07:41.295+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:41.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:07:41.298+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:41.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:41.333+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:07:41.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:07:41.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:07:41.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.056 seconds
[2024-09-28T20:08:11.694+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:11.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:08:11.699+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:08:11.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:11.752+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:08:11.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:08:11.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:11.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.079 seconds
[2024-09-28T20:08:41.873+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:41.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:08:41.875+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:08:41.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:42.003+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:08:41.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:08:42.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:08:42.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.186 seconds
[2024-09-28T20:09:12.147+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:12.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:09:12.150+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:09:12.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:12.169+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:09:12.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:09:12.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:12.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.043 seconds
[2024-09-28T20:09:42.570+0000] {processor.py:186} INFO - Started process (PID=657) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:42.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:09:42.573+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:09:42.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:42.599+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:09:42.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:09:42.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:09:42.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.046 seconds
[2024-09-28T20:10:12.705+0000] {processor.py:186} INFO - Started process (PID=719) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:12.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:10:12.708+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:10:12.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:12.728+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:10:12.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:10:12.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:12.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.039 seconds
[2024-09-28T20:10:43.006+0000] {processor.py:186} INFO - Started process (PID=785) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:43.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:10:43.011+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:10:43.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:43.041+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:10:43.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:10:43.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:10:43.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.055 seconds
[2024-09-28T20:11:13.231+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:13.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:11:13.234+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:11:13.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:13.252+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:11:13.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:11:13.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:13.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.046 seconds
[2024-09-28T20:11:43.448+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:43.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:11:43.451+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:11:43.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:43.466+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:11:43.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:11:43.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:11:43.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.044 seconds
[2024-09-28T20:12:13.728+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:13.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:12:13.730+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:12:13.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:13.742+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:12:13.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:12:13.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:13.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.032 seconds
[2024-09-28T20:12:43.972+0000] {processor.py:186} INFO - Started process (PID=1048) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:43.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:12:43.975+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:12:43.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:43.993+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:12:43.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:12:43.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:12:44.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.038 seconds
[2024-09-28T20:13:14.125+0000] {processor.py:186} INFO - Started process (PID=1114) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:14.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:13:14.127+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:13:14.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:14.142+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:13:14.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:13:14.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:14.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.035 seconds
[2024-09-28T20:13:44.403+0000] {processor.py:186} INFO - Started process (PID=1179) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:44.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:13:44.405+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:13:44.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:44.418+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:13:44.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:13:44.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:13:44.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.033 seconds
[2024-09-28T20:14:14.757+0000] {processor.py:186} INFO - Started process (PID=1245) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:14.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:14:14.759+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:14:14.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:14.773+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:14:14.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:14:14.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:14.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.032 seconds
[2024-09-28T20:14:45.110+0000] {processor.py:186} INFO - Started process (PID=1311) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:45.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:14:45.114+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:14:45.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:45.131+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:14:45.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:14:45.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:14:45.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.040 seconds
[2024-09-28T20:15:15.430+0000] {processor.py:186} INFO - Started process (PID=1377) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:15.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:15:15.432+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:15:15.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:15.447+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:15:15.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:15:15.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:15.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.034 seconds
[2024-09-28T20:15:45.901+0000] {processor.py:186} INFO - Started process (PID=1443) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:45.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:15:45.905+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:15:45.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:45.927+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:15:45.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pluviosidade_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pluviosidade_dag.py", line 8, in <module>
    import oracledb
ModuleNotFoundError: No module named 'oracledb'
[2024-09-28T20:15:45.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:15:45.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.055 seconds
[2024-09-28T20:16:28.250+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:28.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:16:28.262+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:28.303+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:28.431+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.430+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:pluviosidade_dag
[2024-09-28T20:16:28.438+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.438+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:pluviosidade_dag
[2024-09-28T20:16:28.444+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.443+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:pluviosidade_dag
[2024-09-28T20:16:28.448+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.448+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:pluviosidade_dag
[2024-09-28T20:16:28.452+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.452+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:pluviosidade_dag
[2024-09-28T20:16:28.457+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.456+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:pluviosidade_dag
[2024-09-28T20:16:28.461+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.461+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:pluviosidade_dag
[2024-09-28T20:16:28.462+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.461+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:16:28.470+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.470+0000] {dag.py:3262} INFO - Creating ORM DAG for pluviosidade_dag
[2024-09-28T20:16:28.476+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:28.476+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:16:28.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.245 seconds
[2024-09-28T20:16:59.051+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:59.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:16:59.054+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:59.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:59.083+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:16:59.096+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:59.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:16:59.111+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:16:59.111+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:16:59.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.080 seconds
[2024-09-28T20:17:29.399+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:29.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:17:29.401+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:29.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:29.432+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:29.447+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:29.446+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:17:29.464+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:29.464+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:17:29.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.095 seconds
[2024-09-28T20:17:59.853+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:59.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:17:59.855+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:59.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:59.882+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:17:59.896+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:59.896+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:17:59.911+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:17:59.910+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:17:59.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.075 seconds
[2024-09-28T20:18:30.232+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:18:30.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:18:30.234+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:18:30.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:18:30.262+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:18:30.276+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:18:30.276+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:18:30.292+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:18:30.292+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:18:30.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.077 seconds
[2024-09-28T20:19:00.523+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:00.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:19:00.526+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:00.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:00.555+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:00.569+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:00.568+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:19:00.583+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:00.583+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:19:00.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.078 seconds
[2024-09-28T20:19:30.845+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:30.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:19:30.848+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:30.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:30.885+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:19:30.900+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:30.899+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:19:30.915+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:19:30.915+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:19:30.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.087 seconds
[2024-09-28T20:20:01.277+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:01.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:20:01.279+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:01.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:01.310+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:01.328+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:01.327+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:20:01.345+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:01.345+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:20:01.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.087 seconds
[2024-09-28T20:20:31.604+0000] {processor.py:186} INFO - Started process (PID=622) to work on /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:31.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pluviosidade_dag.py for tasks to queue
[2024-09-28T20:20:31.606+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:31.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:31.641+0000] {processor.py:925} INFO - DAG(s) 'pluviosidade_dag' retrieved from /opt/airflow/dags/pluviosidade_dag.py
[2024-09-28T20:20:31.656+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:31.656+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-28T20:20:31.671+0000] {logging_mixin.py:190} INFO - [2024-09-28T20:20:31.671+0000] {dag.py:4180} INFO - Setting next_dagrun for pluviosidade_dag to 2024-10-05 00:00:00+00:00, run_after=2024-11-05 00:00:00+00:00
[2024-09-28T20:20:31.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pluviosidade_dag.py took 0.084 seconds
